# Generated by Django 4.0.6 on 2022-08-26 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0004_advertfeature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='advert',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adverts.advertcategory'),
        ),
        migrations.AddField(
            model_name='advert',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='advertresponse',
            name='advert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adverts.advert'),
        ),
    ]
