import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import Header from '../../components/Header'


const Hello = (props) => {

    const { title } = props
    return (
        <>
            <Header />

            <Head>
              <title>Hello world!</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>


            <Link href="/"><a className="ggg">Main page</a></Link>
            <div>{title}</div>


            <Image src="/nature.jpg" width={200} height={150} layout="responsive" sizes="3000px"/>

        </>
    )
}

export default Hello

export async function getServerSideProps({ query, req }){


    return {
        props: {
            title:"Hello World!11111"
        }
    }
}
